ORG 0000H
		MOV DPTR, #LED	;GAN MA SO LED DANG HEX
	RESET:
		MOV R0,#0		;BO DEM SO R0
		MOV R4,#0		;BO LAP 1 SO			
	MAIN:
		MOV A,R0		;GAN SO HIEN TAI VAO A
		MOV B,#10		;GAN 10 VAO B
		DIV AB			;LAY A CHIA B CHECK SO HANG CHUC A THUONG SO B SO DU
		;
	NHAY:
		MOVC A,@A+DPTR	;DUA MA SO HANG CHUC
		MOV P0,A		;XUAT RA LED
		;NHAY LED TRAI
		SETB P2.0		;BAT LED TRAI
		CLR P2.1		;TAT LED PHAI
		CALL BLINK
		CLR P2.0		;TAT LED TRAI
		;
		MOV A,B			;DUA SO HANG DON VI
		MOVC A,@A+DPTR
		MOV P0,A		;XUAT RA LED
		;NHAY LED PHAI
		SETB P2.1		;BAT LED PHAI
		CLR P2.0		;TAT LED TRAI
		CALL BLINK
		CLR P2.1		;TAT LED TRAI
		;LAP LAI NHIEU LAN 1 SO
		INC R4			;TANG GIA TRI R4
		CJNE R4, #20, MAIN 	;NEU R4 BANG 50 THI TANG SO CON KO THI TIEP TUC HIEN THI
		;
		MOV R4,#0
		INC R0			;TANG GIA TRI
		CJNE R0,#100,MAIN	;NEU R0 KHAC 100 THI QUAY VE MAIN
		JMP RESET			;RESET KHI DA DAT DEN SO 99
	BLINK:
		MOV R1,#1
		DELAY1:
			MOV R2,#100
		DELAY2:
			MOV R3,#100
			DJNZ R3,$
			DJNZ R2,DELAY2
			DJNZ R1,DELAY1
		
		RET
	LED:
	DB 0C0H, 0F9H, 0A4H, 0B0H, 99H, 92H, 82H, 0F8H, 80H, 90H	
END